#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )" || exit
source ./taskidy.sh

#- short description
#+ Some long
#+ description
task:hello() {
  echo "Hello!" "$@"
}

task:print-before-exe() {
  (set -x; echo "YAY!" "$@")
}

task:exit-on-fail() {
  set -e
  echo "Before"
  cat /tmp/sdfdsfdfgfghfghs
  echo "After"
}

task:exit-on-fail-skip() {
  set -e
  echo "Before"
  cat /tmp/sdfdsfdfgfghfghs || true
  echo "After"
}

#- the default task
#+ The task that is execute if no task is
#+ provided on the CLI.
task:default() {
  echo "default" "$@"
}
